# Docker-specific configuration profile for auth-service
# This profile is activated when running in Docker containers
# Use: java -jar app.jar --spring.profiles.active=docker

spring:
  # Redis configuration for Docker environment
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 60000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    
  # Docker-specific database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:ems-postgres}:${DB_PORT:5432}/${DB_NAME:ems_auth}
    username: ${DB_USERNAME:ems_user}
    password: ${DB_PASSWORD:ems_password}

logging:
  level:
    com.ecogrid.ems.auth: DEBUG
    org.springframework.data.redis: ERROR  # Suppress Redis connection errors
    io.lettuce.core: ERROR                 # Suppress Lettuce Redis client errors